services:
  datasharing_db:
    image: postgres
    container_name: send_db    
    restart: unless-stopped
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - send_data:/var/lib/postgres/data
      - type: bind
        source: ./backup
        target: /backup
    environment:
      - POSTGRES_HOST=datasharing_db
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: /bin/sh -c 'echo "#! /bin/sh" >> /bin/send_dump &&
      echo "pg_dump --dbname=postgresql://postgres:example@datasharing_db:5432/postgres -f ./backup/backup.sql" >> /bin/send_dump &&
      chmod u+x /bin/send_dump &&
      docker-entrypoint.sh -c "shared_buffers=256MB" -c "max_connections=200"'
    networks:
      send_net:

  send_backend:
    container_name: send_backend
    image: rallendes/send_backend
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - send_data:/etc/data
    networks:
      send_net:
    depends_on:
      - datasharing_db

  send_builder:
    container_name: send_builder
    image: rallendes/send_provider
    restart: unless-stopped
    ports:
      - 127.0.0.1:4200:80 
    networks:
      send_net:
    depends_on:
      - datasharing_db

volumes:
  send_data:
    name: send_volume

networks:
  send_net:
    driver: bridge