services:
  db:
    image: postgres
    container_name: datasharing_db    
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - datasharing_data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      datasharing_net:
        # ipv4_address: 172.0.0.2      

  api:
    container_name: datasharing_backend
    image: rallendes/datasharing_backend
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - datasharing_data:/etc/data
    networks:
      datasharing_net:
        # ipv4_address: 172.0.0.1

  builder:
    container_name: datasharing_builder
    image: rallendes/datasharing_builder
    restart: unless-stopped
    ports:
      - 4200:80 
    networks:
      datasharing_net:
        # ipv4_address: 172.0.0.3
    
  


volumes:
  datasharing_data:
    name: datasharing_volume

networks:
  datasharing_net:
    driver: bridge
    # ipam: 
    #   config:
    #   - subnet: 172.0.0.0/8
    #     gateway: 172.0.0.254


